"""Task 9 — Generate sentence embeddings for article content.

Model: paraphrase-multilingual-MiniLM-L12-v2 (local, CPU inference)
  - 384-dim vectors, multilingual (Arabic + English in same space)
  - ~120MB download on first run, cached at ~/.cache/huggingface/
  - ~50-150ms per sentence on CPU — acceptable for background worker
  - Zero API quota, zero cost, no external dependency

What gets embedded
------------------
We build one text per article by concatenating headline + summary:

    "<headline>. <summary>"

Why this beats headline-only:
  - Headlines are 8-15 words — they capture topic but not specifics.
    Two headlines can be close in vector space just because they share
    a region or theme, producing false-positive contradiction pairs.
  - Summaries (2-3 sentences, generated by task7.5) contain the
    specific facts: locations, named actors, casualty figures, dates.
    Two summaries about the same event embed very close; two summaries
    about different events in the same region embed further apart.
  - Concatenating both gives the model the topic signal AND the
    specifics signal in a single vector — best of both.

Fallback logic (nothing blocks):
  - No summary yet (task7.5 hasn't run): embed headline only.
  - Arabic preferred over English throughout (platform is Arabic-first).
  - English-only sources (AP, Reuters, BBC…) use their English headline
    + English summary. Both land in the same multilingual vector space
    so cross-lingual contradiction detection still works.

Pipeline ordering note:
  Task7.5 (summarise) must run before task9 to get the richer embedding.
  If task9 runs first it will embed the headline only and set embedding IS NOT NULL,
  so it won't be re-processed when the summary arrives later. For this reason
  task9 is scheduled AFTER task7.5 in the NLP scheduler.

Future upgrade path: OpenAI text-embedding-3-small at $0.02/1M tokens
  (~$0.004/month at current scale). See docs/BUDGET.md.
"""
import logging
import os

from backend.shared.database import get_db_connection

log = logging.getLogger(__name__)

# L12 (12-layer) multilingual paraphrase model — the only multilingual MiniLM variant
# that actually exists on HuggingFace. The L6 variant does NOT exist and causes 404.
# L12 loads ~480MB; Railway Hobby plan (~1GB RAM) handles this fine.
# Render free tier (512MB) was too tight for L12, but worker is now on Railway — not Render.
MODEL_NAME = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"

# Module-level cache — model loads once per worker process, not per cycle.
# Call release_model() after run_task9() completes to free RAM before task11 loads.
_model = None


def _get_model():
    """Lazy-load the sentence-transformers model. Cached after first call."""
    global _model
    if _model is None:
        try:
            from sentence_transformers import SentenceTransformer
            log.info(f"[Task9] Loading embedding model {MODEL_NAME} (first run may download ~80MB)...")
            # HuggingFace now requires a token even for public model downloads.
            # Pass HF_TOKEN if available — harmless when not set but needed on Railway.
            hf_token = os.getenv("HF_TOKEN") or None
            _model = SentenceTransformer(MODEL_NAME, token=hf_token)
            log.info("[Task9] Model loaded.")
        except ImportError:
            log.error("[Task9] sentence-transformers not installed — run: pip install sentence-transformers")
            return None
        except Exception as e:
            log.error(f"[Task9] Failed to load model: {e}")
            return None
    return _model


def release_model():
    """
    Explicitly free the embedding model from RAM.
    Called by the scheduler after run_task9() completes so the ~200MB is
    reclaimed before the next tasks run. The model reloads on the next cycle
    (adds ~2s cold start, acceptable for a 15-minute background job).
    """
    global _model
    if _model is not None:
        import gc
        _model = None
        gc.collect()
        log.info("[Task9] Embedding model released from RAM.")


def _build_embed_text(headline: str | None, summary: str | None) -> str | None:
    """
    Combine headline and summary into the text we will embed.

    Priority:
      1. headline + summary  (richest signal — specific facts + topic)
      2. headline only       (summary not yet generated)
      3. summary only        (rare edge case — headline missing)
      4. None                (nothing available — skip this article)
    """
    h = (headline or "").strip()
    s = (summary  or "").strip()

    if h and s:
        # Trim summary to 400 chars — model context window is 512 tokens.
        # A 400-char summary is ~80 tokens; headline is ~15 tokens → total ~95,
        # well within the 512-token limit.
        return f"{h}. {s[:400]}"
    if h:
        return h
    if s:
        return s[:400]
    return None


def get_embeddings_local(texts: list[str], batch_size: int = 32) -> list[list[float] | None]:
    """Embed a list of texts locally. Returns one 384-dim vector per input, or None on failure."""
    model = _get_model()
    if model is None:
        return [None] * len(texts)

    results: list[list[float] | None] = []
    for i in range(0, len(texts), batch_size):
        batch = texts[i:i + batch_size]
        try:
            vecs = model.encode(batch, show_progress_bar=False, convert_to_numpy=True)
            for vec in vecs:
                results.append(vec.tolist())
        except Exception as e:
            log.warning(f"[Task9] Batch {i}–{i+len(batch)} failed: {e} — appending Nones")
            results.extend([None] * len(batch))

    return results


def run_task9():
    log.info("[Task9] Starting embedding generation...")

    with get_db_connection() as conn:
        with conn.cursor() as cur:
            cur.execute("""
                SELECT
                    article_id,
                    -- Prefer Arabic fields (platform is Arabic-first)
                    COALESCE(headline_ar, headline_en)   AS headline,
                    COALESCE(summary_ar,  summary)       AS summary
                FROM articles
                WHERE (headline_ar IS NOT NULL OR headline_en IS NOT NULL)
                  AND embedding IS NULL
                ORDER BY article_id
                LIMIT 100
            """)
            rows = cur.fetchall()

    if not rows:
        log.info("[Task9] No articles need embedding.")
        return 0

    # Build embed texts and track which used summary vs headline-only
    article_ids  = []
    embed_texts  = []
    has_summary  = 0

    for article_id, headline, summary in rows:
        text = _build_embed_text(headline, summary)
        if text is None:
            continue
        article_ids.append(article_id)
        embed_texts.append(text)
        if summary:
            has_summary += 1

    if not embed_texts:
        log.info("[Task9] No embeddable text found.")
        return 0

    log.info(
        f"[Task9] Embedding {len(embed_texts)} articles "
        f"({has_summary} with summary, {len(embed_texts)-has_summary} headline-only)"
    )

    embeddings = get_embeddings_local(embed_texts)

    stored = 0
    with get_db_connection() as conn:
        with conn.cursor() as cur:
            for article_id, embedding in zip(article_ids, embeddings):
                if embedding is None:
                    continue
                cur.execute("""
                    UPDATE articles
                    SET embedding     = %s::vector,
                        processed_nlp = TRUE
                    WHERE article_id = %s
                """, (str(embedding), article_id))
                stored += 1
        conn.commit()

    log.info(f"[Task9] Complete — {stored}/{len(embed_texts)} embeddings stored")
    return stored
